### ISSUE TITLE
Multiple Connections

### ISSUE THREAD

**Issue by Maat5** [Mockgoose/Mockgoose#15]
Hi , I was wondering if already exists a way to close multiple connections, currently I'm creating connections with `mongoose.createConnection(uri, connectionParams , callback )` , but when try to remove all the collections from the temporaty store with `mockgoose.helper.reset()` I got the next Error:

`TypeError: Cannot read property 'dropDatabase' of undefined`

**Comment by winfinit** [comment]
@Maat5 can you please share snippet that will demonstrate this issue? I see that in our test case, in index.js, reset() is passing, but there is only one connection.

**Comment by Maat5** [comment]
@winfinit Sure, thanks for answering so soon. I'm using Mocha to handle my tests
```
// create connection to first database
before("DB1 connection", (done) => {
  mockgoose.prepareStorage().then(function() {
    mongoose.passer = mongoose.createConnection(uriDB1, { user: "fakeUser", password: "fakePass" }, (err, res) => {
      if (err) throw err;
      winston.test("connected to", uriDB1);
      done(err);
    });
  });
}); 

// create connection to second database
before("DB2 connection", (done) => {
  mockgoose.prepareStorage().then(function() {
    mongoose.system = mongoose.createConnection(uriDB2, { user: "fakeUser", password: "fakePass" }, (err, res) => {
      if (err) throw err;
      winston.test("connected to", uriDB2);
      done(err);
    });
  });
});

// remove collections from a temporary store
after("Drop db",(done) => {
  // Here is when the error is trigged
  mockgoose.helper.reset().then(function() {
    done();
  });
});
```

I really don't know if this is the correct approach to handle multiple connections with Mockgoose for my tests, let me know if exists another way.

Thanks !

**Comment by winfinit** [comment]
Thank you, I am able to duplicate this issue now

**Comment by petershaw** [comment]
Same here: 

```
	before(function (done) {
		mockgoose.prepareStorage().then(function() {
			mongoose.connect('mongodb://localhost/TestingDISPLAYS', function(err) {
				done(err);
			});
		});
	});
```

Get an: (node:28266) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): TypeError: Cannot read property 'dropDatabase' of undefined

**Comment by JohnProg** [comment]
HI guys, any update? I'm getting the same error.

**Comment by winfinit** [comment]
I was able to duplicate this issue, but didn't have a time to work on a fix yet. This weekend looks promising so far :) I am very interested to solve this problem.

**Comment by petershaw** [comment]
Hi winfinit, 

thanks a lot for looking deeper into this. We appreciate your work in free software. 
Currently we are sticked to Version 6.0.8, because the HEAD destroys all our projects. Besides we are not a huge fan of promises or new api design, but we are a fan of mockgoose. 
What makes a lot of confusion in our office is a release, that does not work, even not from the code of the documentation. Uhhh, npm's eco-system. 
Please let us know if we can help in any way to help improving the release strategy. Demo-Testing, CI-Server support, Unit-Test writing, ect... We are strongly believe in mockgoose and build a lot of stuff onto it. 

Thanks a lot, keep on the good job.

**Comment by winfinit** [comment]
@petershaw thank you for your feedback, however I am puzzled by some of your comments. 

Release does work for some or even most of the users, if there are cases when it doesn't, just report an issue, such as this one, and if one would like to be extra nice, submit your test case. Each bug is included in a test directory to ensure that next patch/minor/major release won't break same functionality.

As far as promises, I prefer that over callbacks, and you can see that with new major library releases, such as Angular 2, promises and observables are your only options. I do understand that some people prefer old or original approach, but from what I see, community is moving away from them.

Any help is greatly appreciated and thanks again for your feedback.

**Comment by winfinit** [comment]
@Maat5 can you please test this issue with new 7.0.7 release?
+ mockgoose@7.0.7

**Comment by Maat5** [comment]
Hi @winfinit ! I tested again with 7.0.7 release, now I didn't get the initial error of this thread, but now `mockgoose.helper.reset()` remove the databases itself and not the temporaty ones

**Comment by winfinit** [comment]
oh wow, thats not good... it is interesting why connections structure would have live db connections, but in any case, that is something that i need to account for, will produce a new patch release soon

**Comment by winfinit** [comment]
@Maat5 I am still a bit confused how this could happen for you. at this point I've ran numerous tests and I wasn't able to duplicate this behavior....

It would be great if you can explain in more detail your setup, because mockgoose for every mocked instance overloads connection, so connections object of mongoose should never contain a real connection to a real db.

but obviously it did happen for you, so I've added a temporary hack to avoid such behaviors (without me understanding how such behavior can occur), that will ensure that mockgoose will only touch its connections.

+ mockgoose@7.1.1
