### ISSUE TITLE
Mockgoose 7 Downloading Data During Test Run

### ISSUE THREAD

**Issue by calvinkcox** [Mockgoose/Mockgoose#17]
After installing all required dependencies and setting up my tests my console output is repeatedly trying to download something...

Completed: 8.8 % (6.8mb / 77.5mbmbb

I've found other references on stack overflow of the same issue.
I've attempted uninstalling and reinstalling mockgoose, as well as deleting all node_modules.

Calvin

**Comment by winfinit** [comment]
it is downloading mongodb, but it should only do it one time, after that it will use it from its temp cache, unless you are killing container all the time

**Comment by calvinkcox** [comment]
@winfinit Thanks! I determined that even with the updated timeout the download was never completing. It would be nice if there was a way to pre-download the mongodb code. I assumed adding mongodb-prebuilt to my package.json would do such, but that is not working either.

**Comment by winfinit** [comment]
@calvinkcox hmm, that might be a good idea, i will think about how to make it happen, thank you for reporting this issue

**Comment by neverfox** [comment]
Yes, it would be very nice if one could preinitialize mockgoose storage completely outside of the test framework. I use a Docker image as a build environment and would like to just bake it into the image so that when the source code is mounted as a volume and I run the tests, it just flies through. I tried doing a `prepareStorage` step in the image build, and that worked as far as forcing a download, but calling `prepareStorage` again in the test isn't idempotent, i.e. it downloads again. If I remove the call in the test, the test hangs (not to mention that removing it from the test is not something I want to do, since it might be necessary in another context). If there were at least a way to tell `prepareStorage` to not download if it's already done, that would be workable.

**Comment by winfinit** [comment]
@neverfox there is an option in latest release to not download release if it is already downloaded, so just before making your docker image, make sure that you run prepare storage first time, then create your image with specifying version against which you want to work

**Comment by t3hmrman** [comment]
Just for anyone who might wander into this issue searching for how to turn this off, it seems like this functionality is enabled by [specifying the desired mongo version](https://github.com/Mockgoose/Mockgoose/issues/20#issuecomment-291613538).

The code:
```js
mockgoose.helper.setDbVersion("3.2.1");
```

@winfinit is that right?
