### ISSUE TITLE
mongodb-prebuilt downloads 235 MB mongodb package in the background when running your first test

### ISSUE THREAD

**Issue by leonidumanskiy** [Mockgoose/Mockgoose#19]
Hi,
I just spent an hour trying to understand why my test fails with the timeout and it looks like mongodb-prebuild downloads the mongodb-win32-x86_64-latest.zip 235 MB package from the official mongo website when I run **prepareStorage()**.
This shouldn't happen, dependency files should be downloaded when you run npm install and not during the runtime, and definitely not during the npm test.

If that's not possible to fix at the moment, I think we should at least add some sort of warning to the documentation.

**Comment by winfinit** [comment]
pull requests even for documentation are always welcome. it is downloading a package if it is missing, and to do a download and install during npm install is a bit tricky, and previous version with that approach had some issues. 

there was a request somewhere to provide functionality to point mockgoose to already downloaded version of mongodb, so that could be a solution also.

another cool solution could be to just deliver mongod, however i don't want to maintain my own mirror for every OS and release of mongodb.
