### ISSUE TITLE
Helper reset fails

### ISSUE THREAD

**Issue by juusechec** [Mockgoose/Mockgoose#28]
I'm executing the test of mern.io with "mockgoose": "^7.3.1" (other versions is broken).
```javascript
// https://github.com/Hashnode/mern-starter/blob/master/server/util/test-helpers.js
import * as mongoose from 'mongoose';
import {Mockgoose} from 'mockgoose';

let mockgoose: Mockgoose = new Mockgoose(mongoose);

export function connectDB(t, done) {
  mockgoose.prepareStorage().then(() => {
    mongoose.connect('mongodb://localhost:27017/mern-test', err => {
      if (err) t.fail('Unable to connect to test database');
      done();
    });
  });
}

export function dropDB(t) {
  // It fails
  mockgoose.helper.reset().then(() => {
     console.log('Db is erased');
  }).catch((err) => {
     console.log('db is errrors', err);
     if (err) t.fail('Unable to reset test database');
  });
}
```
The dropDB function not erase the database, I'm forced to recursive erase:
```javascript
export function dropDB(t) {
  // It works
  for (let i = 0; i < mockgoose.mongooseObj.connections.length; i++) {
    mockgoose.mongooseObj.connections[i].db.dropDatabase(function(err, result){
        if (err) t.fail('Unable to reset test database');
    });
  }
}
```

**Comment by winfinit** [comment]
@juusechec 7.3.1 is latest version, so this is a version that you should be using, I am not sure tho what you are referring to as "broke", but in any case, as long as it is not broke in 7.3.1 (latest release), this is all I care for.

above dropDB would have bugs in some instances, might not be in yours, but I do remember fixing this snippet.

reset() call will only affect mockgoose created collections, that are being overridden during connection mocking, which do not correspond to db name that is being specified in your connection string.

I am pretty confused what issue you are reporting here, because I do have a test case that is looking at reset(), and it is passing now. Go help me, please create a unit that I can run (preferably via mocha), that can demonstrate this failure.

**Comment by juusechec** [comment]
Yes, you can clone and execute test.
```bash
git clone https://github.com/juusechec/mern-starter-with-errors
cd mern-starter-with-errors
npm install
npm run test
```

In this case I'm obtained the next error.
```bash
[React Intl] Cannot format message: "twitterMessage", using message id as fallback.
Db is erased
Db is erased
Db is erased
Db is erased

   35 passed
   1 failed


   1. server › models › post › Should correctly delete a post
     
  t.is(queriedPost, null)
       |                 
       Object{"$__":Object{strictMode:true,selected:Object{},shardval:null,saveError:null,validationError:null,adhocPaths:null,removing:null,inserting:null,version:null,getters:Object{},_id:null,populate:null,populated:null,wasPopulated:false,scope:null,activePaths:Object{paths:#Object#,states:#Object#,stateNames:#Array#},ownerDocument:null,fullPath:null,emitter:Object{domain:null,_events:#Object#,_eventsCount:0,_maxListeners:0}},isNew:false,errors:null,_doc:Object{dateAdded:Object{},__v:0,content:"Hello Mern says Foo",cuid:"f34gb2bh24b24b2",slug:"bar",title:"bar",name:"Foo",_id:Object{_bsontype:"ObjectID",id:"Buffer\n59 10 f2 6f 3f 9e b7 4a eb 0d c5 dd"}}}
  
      content: 'Hello Mern === null
        _callee4$ (post.spec.js:77:5)
        tryCatch (/home/jorge/workspace/mern-starter-with-errors/node_modules/regenerator-runtime/runtime.js:65:40)
        GeneratorFunctionPrototype.invoke [as _invoke] (/home/jorge/workspace/mern-starter-with-errors/node_modules/regenerator-runtime/runtime.js:303:22)
        GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/jorge/workspace/mern-starter-with-errors/node_modules/regenerator-runtime/runtime.js:117:21)
        process._tickCallback (internal/process/next_tick.js:109:7)

```
The error refer that the posts number after remove by id would be zero (null) and no one (previous post with the same id created in other test case). After each test cases the idea is erase the entire database. This test case is in https://github.com/juusechec/mern-starter-with-errors/blob/master/server/models/__tests__/post.spec.js#L77

**Comment by jeoffreybakker** [comment]
I have the same problem. This is caused by using the dropDatabase helper method in mongoose which is introduced in version (4.6.4). See the related line 32 in mockgoose-helper.ts
``
 connection.dropDatabase((err: any) => {
``

Changing the line to the following will work for us (using mongoose 3.8.12)
``
connection.db.dropDatabase((err: any) => {
``

**Comment by abiaskosty** [comment]
`mockgoose.helper.reset()` didn't work for me as well. 
@winfinit the test case only checks that method has been invoked and finished without errors. But it doesn't check if DB has been dropped or not. 

Inside `reset()` method there is a check `!/mockgoose-temp-db-/.test(connection.name)` which is, in my case, always passed because `connection.name` is always null.
`reset()` method works if I assign `connection.name = connection.db.databaseName` when connection is established. 

@winfinit I would like to send a pull request. What would be the right way to fix it? Use `connection.db.databaseName` in `reset()` method check or set connection name in `ConnectionWrapper.run`?

**Comment by midthun** [comment]
I have a similar issue, `connection.name` is `null` when I set `useMongoClient: true` (or false, just having that option in the `mongoose.connect` call makes mockgoose not recognize then connection), it works otherwise it seems.

**Comment by abiaskosty** [comment]
@midthun yes, it works if I remove `useMongoClient` option, but it's not recommended to do since mongoose v4.11.0 http://mongoosejs.com/docs/connections.html#use-mongo-client.

**Comment by midthun** [comment]
@abiaskosty yes, I was just mentioning it because it might help to track down the issue. You should use `useMongoClient` since if not, you will for now get deprecation warnings.
