### ISSUE TITLE
Mongod shutting down

### ISSUE THREAD

**Issue by jakecoffman** [Mockgoose/Mockgoose#45]
Two test suites using mockgoose running at the same time interfere with each other and error with "Mongod shutting down".

To reproduce, run `npm test &` twice quickly on this repo.

**Comment by winfinit** [comment]
@jakecoffman thank you for reporting this issue. Cause of this is actually same as the one with parallel runs. I think cause of this is same/similar to issue #22 and #18 I will keep this issue open for now, until I know for sure.

**Comment by janstuemmel** [comment]
monkey patched that with: 
```js
....
module.exports.close = () => {
  const proc = mockgoose.mongodHelper.mongoBin.childProcess;
  require('tree-kill')(proc.pid, 'SIGKILL', err => {
    if(err) console.error(err.message);
  });
}
```

**Comment by ellenaua** [comment]
Hi guys! I debugged this issue today, it happens because:
- two tests start simultaneously
- each test creates a new Mockgoose instance
- two Mockgoose instances use this code to detect free port for Mongo
```portfinder.getPort({port: 27017}...```
https://github.com/Mockgoose/Mockgoose/blob/master/src/mockgoose.ts#L68
- both Mockgoose instances get the same port (27017 or 27018 etc)
- then, two Mockgoose instances try to start mongo in this line https://github.com/Mockgoose/Mockgoose/blob/master/src/mockgoose.ts#L42 
- but mongo which was second, produces this log: 
```
[initandlisten] MongoDB starting : pid=208 port=27017 dbpath=/tmp/mockgoose/1521105446274 64-bit host=60df91122e20
[initandlisten] db version v3.7.1-243-g216c0f8
[initandlisten] git version: 216c0f863225609a67a3dcecab3cf0f8d884f511
[initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
[initandlisten] allocator: tcmalloc
[initandlisten] modules: none
[initandlisten] build environment:
[initandlisten]     distmod: debian81
[initandlisten]     distarch: x86_64
[initandlisten]     target_arch: x86_64
[initandlisten] options: { net: { port: 27017 }, storage: { dbPath: "/tmp/mockgoose/1521105446274", engine: "ephemeralForTest" } }
[initandlisten] Failed to set up listener: SocketException: Address already in use
[initandlisten] now exiting
[initandlisten] shutting down with code:48
```

Possible solution: 
-  allow developers to explicitly pass port to Mockgoose
```prepareStorage(port: number): Promise<void> {```

what do you think?

**Comment by jakecoffman** [comment]
This isn't a big deal for me anymore since I switched to Jenkins2 builds which run inside of a container.
